var apiURL= "http://13.233.115.232:8091/predict";
alert("started");
var mediaPageList=[
    "Google News",
    "Reddit News",
    "BBC News",
    "The New York Times",
    "BuzzFeed",
    "AL Jazeera English",
    "Defence Blog",
    "Global Issues",
    "The Cipher Brief",
    "Yahoo News",
    "The Guardian",
    "Reuters",
    "Washington Post World",
    "The Times of India",
    "NDTV",
    "Rt-News",
    "The Independent",
    "SPIEGEL International",
    "NPR",
    "CNBC International",
    "Daily Mirror",
    "CBC News",
    "TIME",
    "CBS News",
    "The Sun",
    "SputnikNews",
    "ABC News",
    "ABC News",
    "Vox",
    "Sky News",
    "The Sydney Morning Herald",
    "RFI English",
    "News24.com",
    "The Raw Story",
    "Euronews World",
    "Global News",
    "CTV News",
    "FRANCE 24",
    "The Seattle Times",
    "Talking Points Memo",
    "CNA",
    "Daily Telegraph",
    "TODAY",
    "The Christian Science Monitor",
    "PRI Public Radio International",
    "Breaking News",
    "War On The Rocks",
    "Evening Express Memories",
    "New Europe",
    "World Affairs Journal",
    "Small Wars Journal",
    "itworld",
    "Looking Times",
    "Asian Defence News Channel",
    "India Today",
    "Indian Express",
    "The Hindu",
    "News18",
    "FirstPost",
    "Business Standard",
    "DNA India",
    "Deccan Chronicle",
    "Oneindia News",
    "The Financial Express",
    "Scroll",
    "The Hindu Business Line",
    "The Quint",
    "Outlookindia",
    "Free Press Journal",
    "Telangana Today",
    " Asian Age",
    "Chandigarh Metro",
    "Daily Excelsior",
    "Teluguglobal",
    "Jaianndata.com",
    "Star Of Mysore",
    "The Navhind Times",
    "Nagpur Today",
    "The Arunachal Times",
    "The Rising Kashmir",
    "Tentaran.com",
    "Yo Vizag",
    "The Sangai Express",
    "Orissapost",
    "Kashmir Reader",
    "Bilkul Online",
    "Moses News",
    "Emit Post India",
    "THE TIMES OF BENGAL",
    "The Himachal News",
    "the NORTHLINES",
    "The Modern Journal",
    "Election Tamasha",
    "The Metro Talk",
    "League Of India",
    "Indian News Queensland",
    "Politically",
    "Newsekaaina",
    "Sports kanazee",
    "Metro Rail News",
    "Indian Spectator",
    "The Eastern Herald",
    "Asba News"
    

];
